Repository kubescape/kollector, pull requests merged in 2024-03, with the labels that each got.

#51 Update pr-merged.yaml
  .github/workflows/pr-merged.yaml
Labels: enhancement, Review effort [1-5]: 1

#52 Fix load creds
  .github/workflows/pr-created.yaml
  .github/workflows/pr-merged.yaml
  go.mod
  go.sum
Labels: enhancement, release, dependencies, Review effort [1-5]: 3

#54 use go 1.21 in Dockerfile
  build/Dockerfile
Labels: enhancement, release, Review effort [1-5]: 1
